// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhE5ZdeDZvqc-doHP0l96MiyBy_-_5XPI',
    appId: '1:327402673821:web:fb19a5c950b6e66880e674',
    messagingSenderId: '327402673821',
    projectId: 'notifications-f8172',
    authDomain: 'notifications-f8172.firebaseapp.com',
    storageBucket: 'notifications-f8172.appspot.com',
    measurementId: 'G-NC32N07RDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALC6t5LfyYnNzBaqLKYTP8duZ7MkLoeng',
    appId: '1:327402673821:android:63e9c9e789a0077c80e674',
    messagingSenderId: '327402673821',
    projectId: 'notifications-f8172',
    storageBucket: 'notifications-f8172.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-JIrEg-57HxGHAsh3kOmGwqpjREOvrA4',
    appId: '1:327402673821:ios:ff360160bba9daef80e674',
    messagingSenderId: '327402673821',
    projectId: 'notifications-f8172',
    storageBucket: 'notifications-f8172.appspot.com',
    iosBundleId: 'com.example.lawyerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-JIrEg-57HxGHAsh3kOmGwqpjREOvrA4',
    appId: '1:327402673821:ios:35b58f95211b8f1d80e674',
    messagingSenderId: '327402673821',
    projectId: 'notifications-f8172',
    storageBucket: 'notifications-f8172.appspot.com',
    iosBundleId: 'com.example.lawyerapp.RunnerTests',
  );
}
